# Site
# repository: sproogen/resume-theme
favicon: images/icon.png

# Personal info
name: João Pedro
full_name: João Pedro Moreira Ferreira
title: Personal
position: Computer Vision M.Sc Student
email: joaopmoferreira@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
scholar: citations?user=QacWVbEAAAAJ&hl=pt-BR&oi=sra
lattes: 0866273910879686
github_username:  jpeumesmo
linkedin_username: jo%C3%A3o-pedro-moreira-ferreira-165a91154
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/profile2.jpg
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins_dir:
 - jekyll-seo-tag
