# Site
# repository: sproogen/resume-theme
favicon: images/icon.png

# Personal info
name: João Pedro
full_name: João Pedro Moreira Ferreira
title: Personal
position: Computer Vision M.Sc Student
email: joaopmoferreira@gmail.com
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: facespics
scholar: citations?user=QacWVbEAAAAJ&hl=pt-BR&oi=sra
lattes: 0866273910879686
github_username:  jpeumesmo
linkedin_username: jo%C3%A3o-pedro-moreira-ferreira-165a91154
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/profile2.jpg
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's João Pedro and I'm a Master student in computer vision and machine learning. I'm currently working on <mark>GAN's</mark> and <mark>GCN's</mark>.  Also, work as a developer during graduation solving issues on web systems and infrastructure of the distance education nucleus of the university.  During my career, I have worked with different teams on several projects and gain experience in teamwork and Agile software development.

  I am most skilled in: <mark>Computer Vision</mark> and <mark>Machine Learning</mark>
  
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs
#   Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#    - Rock climbing
#    - Gaming
#    - Knitting
#    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false
# darkmode: true
# Build settings
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins_dir:
 - jekyll-seo-tag

gtag: UA-149430375-1